airflow:
  connections:
    - conn_id: snowflake_default
      conn_type: snowflake
      login: TANISHQP
      password: T@nishq@TDG2026
      schema: PUBLIC
      extra: |
        {
          "account": "mec74339.us-east-1",
          "warehouse": "COMPUTE_WH",
          "database": "ASTRO",
          "role": "ACCOUNTADMIN"
        }
